# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Variable 'Alias' was defined in the Variables tab
# Variable 'DomainName' was defined in the Variables tab
# Variable 'DomainSuffix' was defined in the Variables tab
# Variable Group 'Key-Vault' was defined in the Variables tab

trigger: none

jobs:
- job: Job
  displayName: Set Version, Export, Check, Commit
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    persistCredentials: True
  - task: PowerPlatformToolInstaller@2
    displayName: 'Tool Installer '
  - task: PowerShell@2
    displayName: Parse Branch Path
    inputs:
      filePath: scripts/Parse-BranchPath.ps1
      arguments: -BranchPath $(Build.SourceBranchName)
      warningPreference: silentlyContinue
      informationPreference: silentlyContinue
  - task: PowerShell@2
    displayName: Parse Solution Version
    inputs:
      filePath: scripts/Parse-SolutionVersion.ps1
      arguments: -DomainName $(DomainName) -DomainSuffix $(DomainSuffix) -SolutionName $(SolutionName) -ClientID $(Dev-Deployment-App-Client-ID) -ClientSecret $(Dev-Deployment-App-Client-Secret) -MajorIncrement '0' -MinorIncrement '0' -BuildIncrement '0' -RevisionIncrement '1'
  - task: PowerPlatformSetSolutionVersion@2
    displayName: 'Set Solution Version '
    inputs:
      authenticationType: PowerPlatformSPN
      PowerPlatformSPN: https://$(DomainName).$(DomainSuffix)/
      SolutionName: $(SolutionName)
      SolutionVersionNumber: $(Major).$(Minor).$(Build).$(Revision)
  - task: PowerPlatformPublishCustomizations@2
    displayName: 'Publish Customizations '
    inputs:
      authenticationType: PowerPlatformSPN
      PowerPlatformSPN: https://$(DomainName).$(DomainSuffix)/
      Environment: ''
  - task: PowerPlatformExportSolution@2
    displayName: 'Export Unmanaged Solution '
    inputs:
      authenticationType: PowerPlatformSPN
      PowerPlatformSPN: https://$(DomainName).$(DomainSuffix)/
      Environment: ''
      SolutionName: $(SolutionName)
      SolutionOutputFile: $(System.ArtifactsDirectory)\solutions\$(SolutionName).zip
      ExportAutoNumberingSettings: true
      ExportCalendarSettings: true
      ExportCustomizationSettings: true
      ExportEmailTrackingSettings: true
      ExportExternalApplicationSettings: true
      ExportGeneralSettings: true
      ExportIsvConfig: true
      ExportMarketingSettings: true
      ExportOutlookSynchronizationSettings: true
      ExportRelationshipRoles: true
      ExportSales: true
  - task: PowerPlatformExportSolution@2
    displayName: Export Managed Solution
    inputs:
      authenticationType: PowerPlatformSPN
      PowerPlatformSPN: https://$(DomainName).$(DomainSuffix)/
      Environment: ''
      SolutionName: $(SolutionName)
      SolutionOutputFile: $(System.ArtifactsDirectory)\solutions\$(SolutionName)_managed.zip
      Managed: true
      ExportAutoNumberingSettings: true
      ExportCalendarSettings: true
      ExportCustomizationSettings: true
      ExportEmailTrackingSettings: true
      ExportExternalApplicationSettings: true
      ExportGeneralSettings: true
      ExportIsvConfig: true
      ExportMarketingSettings: true
      ExportOutlookSynchronizationSettings: true
      ExportRelationshipRoles: true
      ExportSales: true
  - task: PowerPlatformChecker@2
    displayName: Check Solutions
    inputs:
      PowerPlatformSPN: https://$(DomainName).$(DomainSuffix)/
      FilesToAnalyze: $(System.ArtifactsDirectory)\solutions\*.zip
      RuleSet: 0ad12346-e108-40b8-a956-9a8f95ea18c9
      ErrorLevel: CriticalIssueCount
  - task: PowerPlatformUnpackSolution@2
    displayName: Unpack Solutions
    inputs:
      SolutionInputFile: $(System.ArtifactsDirectory)\solutions\$(SolutionName).zip
      SolutionTargetFolder: $(System.DefaultWorkingDirectory)\solutionSrc\$(SolutionName)
      SolutionType: Both
  - task: CmdLine@2
    displayName: Commit to user branch
    inputs:
      script: >
        git config user.email $(Build.RequestedForEmail)
        git config user.name $(Build.RequestedFor)
        git checkout users/$(Alias)/$(Build.SourceBranchName)
        git add --all
        git commit -m "Commit $(SolutionName) to $(Build.SourceBranchName)"
        git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin users/$(Alias)/$(Build.SourceBranchName)
  - task: PublishPipelineArtifact@1
    displayName: Publish Solutions Artifact
    inputs:
      path: $(System.ArtifactsDirectory)\solutions
      artifactName: Solutions